### PR TITLE
WIP: Scala 2.12.0-RC1

### PR DESCRIPTION
**Pull request by larsrh**

### CODE REVIEW

**Comment by larsrh** [comment]
This yak is way hairier than I anticipated. Dependent projects include http4s and a lot of Scala.js stuff.

**Comment by alexarchambault** [comment]
The fetch-js, web, and http-server could be compiled only for 2.11, if they're a problem. Like cli should already be.

**Comment by larsrh** [comment]
I might be able to get `fastparse` out for 2.12, but beyond that, no promises :smile:

**Comment by alexarchambault** [comment]
@larsrh I prepared `build.sbt` a bit more [here](https://github.com/alexarchambault/coursier/pull/368). With fastparse and https://github.com/scala-js/scala-js-jquery (you were already on the latter too it seems :-), that should be good for `2.12.0-RC2`.

**Comment by larsrh** [comment]
OK, closing this in favour of #368.

**Pull request closed without merging**
