### PR TITLE
Cross compile for Scala 2.12.0-RC2

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by larsrh** [comment]
The fastparse commit I'd like to release I currently running on Travis CI, which may take a while. I'll ping you when it's done.

**Comment by larsrh** [comment]
fastparse 0.4.2 is now available.

**Comment by larsrh** [comment]
woot!

**Comment by alexarchambault** [comment]
@larsrh So `1.0.0-M14-6` was published, supporting `2.12.0-RC2`.

**Comment by alexarchambault** [comment]
Thanks for having pushed for it :-).

**Pull request merged**
