### PR TITLE
Bugfix/#131 junk sha1

### LINKED ISSUE #131: SHA1 sums with too much junk not handled fine
Occurs for `org.apache.spark:spark-sql_2.11:1.2.0` from Central... but not with the one from JCenter!

junk:
```
$ curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql_2.11/1.2.0/spark-sql_2.11-1.2.0.pom.sha1
./spark-sql_2.11/1.2.0/spark-sql_2.11-1.2.0.pom:
EBCE 8C6D 3CEB 5C55 B257  EFF0 14F4 BA13 AEB4 BAE7
```

no junk:
```
$ curl https://jcenter.bintray.com/org/apache/spark/spark-sql_2.11/1.2.0/spark-sql_2.11-1.2.0.pom.sha1
ebce8c6d3ceb5c55b257eff014f4ba13aeb4bae7
```

### PR DESCRIPTION
**Pull request by darkjh**
Fix #131 with unit tests on checksum.
For the moment tests are done using fixtures. Afterwards with some refactoring we could mock parts of the logic and avoid fixtures.

### CODE REVIEW

**Comment by darkjh** [comment]
retest

**Comment by darkjh** [comment]
Seems that I don't have the right to relaunch travis ...

**Comment by alexarchambault** [comment]
@darkjh No problem, that's the Scala JS tests that tend to transiently fail more and more often on the Mac CI... I already tried to re-run them.

**Comment by alexarchambault** [comment]
Hey @darkjh :-) As I told you via other channels, it should be possible to download some of the fixtures from Central. These are not supposed to change I think.

I have some plans to make the checksum handling better, we'll discuss that!

**Comment by alexarchambault** [comment]
Thanks @darkjh :-)

As a side note, this modifies somehow touchy (because poorly tested, like the whole `cache` module - `core` is fine OTOH) parts of coursier, namely checksum calculation. I'll either start adding the integration tests I've wanting to add for some time, or test that locally at length, before the next milestone.

**Pull request merged**
