### PR TITLE
Basic property substitution in version in POMs

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
Fixes https://github.com/alexarchambault/coursier/issues/210.

**Comment by alexarchambault** [comment]
@pfn I had to ensure coursier gives the maven-plugin packages the .jar extension (https://github.com/alexarchambault/coursier/pull/213/commits/f167b36c1c3416641817b9e2fe7f30d581c87c54), for https://github.com/pfn/android-javacv-sample to be fine. I guess that's their actual extension, right?

**Comment by pfn** [comment]
@alexarchambault yes, that's correct, `maven-plugin` packaging = `jar`; however, they do not get exported to classpath by default (but if coursier is only doing resolution/fetching, shouldn't matter); they only get exported to classpath if one sets `classpathTypes += "maven-plugin"`

**Comment by alexarchambault** [comment]
Seriously? I didn't know about that one :). Opened https://github.com/alexarchambault/coursier/issues/214 for it.

**Pull request merged**
