### PR TITLE
Fix version interval bug from kinesis producer pom.xml

### PR DESCRIPTION
**Pull request by eboto**
Originally found when trying to import [the latest amazon kinesis producer library's pom.xml](https://repo1.maven.org/maven2/com/amazonaws/amazon-kinesis-producer/0.12.0/amazon-kinesis-producer-0.12.0.pom)

Repros issue #355

Also fixes the breaking test `coursier.test.CentralTests.versionInterval`

### CODE REVIEW

**Comment by eboto** [comment]
Because there are existing test failures, the relevant part here was:
```
Failure('utest.AssertionError: assert(itv5 == Some(VersionInterval(Some(Version("1.11.0")), Some(Version("1.12.0")), false, true)))
```
which disappeared in the second run

**Comment by eboto** [comment]
I think the travis failure is spurious -- some SSL exception in resolving the project: 
```
[info] Fetched artifacts of coreJVM
coursier.ResolutionException: 1 download error
  Caught javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset (Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset)
[error] (coreJVM/*:update) coursier.ResolutionException: 1 download error
[error]   Caught javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset (Connection has been shutdown: javax.net.ssl.SSLException: 
```

**Comment by alexarchambault** [comment]
Thanks for that! I'll merge as soon as the CI is green (which it should be anytime soon, I think the previous error was spurious).

**Comment by alexarchambault** [comment]
Merging, thanks!

**Pull request merged**
